version: '2'

volumes:
  redmine-themes:
  redmine-plugins:
  redmine-initdb:
  redmine-database:

services:
  redmine-themes:
    image: dmitriiageev/redmine-themes
    volumes:
      - redmine-themes:/usr/src/redmine/public/themes

  redmine-plugins:
    image: dmitriiageev/redmine-plugins
    volumes:
      - redmine-plugins:/usr/src/redmine/plugins
      - redmine-initdb:/docker-entrypoint-initdb.d/mysql

  # To create a database dump use:
  # docker exec some-mysql sh -c 'exec mysqldump --all-databases -uroot -p"$MYSQL_ROOT_PASSWORD"' > /some/path/on/your/host/all-databases.sql
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    depends_on:
      - redmine-plugins
    environment:
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - redmine-initdb:/docker-entrypoint-initdb.d
      - redmine-database:/var/lib/mysql

  redmine:
    image: redmine
    restart: always
    depends_on:
      - mysql
      - redmine-plugins
      - redmine-themes
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_PORT: 3306
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: password
      REDMINE_PLUGINS_MIGRATE: "yes"
    ports:
      - 80:3000
    volumes:
      - redmine-themes:/usr/src/redmine/public/themes
      - redmine-plugins:/usr/src/redmine/plugins
